# Generated by Django 4.1.7 on 2023-05-26 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, help_text='Укажите время, требуемое для приготовления этого рецепта (в минутах)', validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть меньше 1 минуты!'), django.core.validators.MaxValueValidator(6000, 'Время приготовления не может быть более 100 часов!')], verbose_name='Время приготовления'),
        ),
    ]
