# Generated by Django 4.1.7 on 2023-05-27 10:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_recipe_ingredients_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorited',
            field=models.ManyToManyField(help_text='Избранное', null=True, related_name='favorited_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='in_shopping_cart',
            field=models.ManyToManyField(help_text='Корзина', null=True, related_name='in_cart_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Количество продукта', validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиента не может быть меньше 1!')], verbose_name='Количество'),
        ),
    ]
