# Generated by Django 4.1.7 on 2023-05-27 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_alter_recipe_favorited_alter_recipe_in_shopping_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='in_shopping_cart',
            field=models.ManyToManyField(blank=True, help_text='Корзина', related_name='in_cart_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Корзина'),
        ),
    ]
